# frontend/cloudbuild.yaml
substitutions:
  _PROJECT_ID: ""
  _REGION: ""
  _AR_REPO: ""
  _ENV_LOWER: ""
  _TAG: ""
  _BUILD_MODE: "production"

steps:
  - name: gcr.io/cloud-builders/docker
    id: Build frontend image
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/frontend-${_ENV_LOWER}:${_TAG}
      - --build-arg
      - BUILD_MODE=${_BUILD_MODE}
      - -f
      - Dockerfile          # ← 현재 디렉터리 기준
      - .                   # ← 현재 디렉터리를 컨텍스트로.

  - name: gcr.io/cloud-builders/docker
    id: Push image
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/frontend-${_ENV_LOWER}:${_TAG}

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/frontend-${_ENV_LOWER}:${_TAG}
