# frontend/cloudbuild.yaml
substitutions:
  _PROJECT_ID: ""
  _REGION: ""
  _AR_REPO: ""
  _ENV_LOWER: ""
  _TAG: "local"
  _BUILD_MODE: "production"

steps:
  - name: gcr.io/cloud-builders/docker
    dir: frontend
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/frontend-${_ENV_LOWER}:${_TAG}
      - --build-arg
      - BUILD_MODE=${_BUILD_MODE}
      - -f
      - Dockerfile
      - .

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/frontend-${_ENV_LOWER}:${_TAG}