name: Deploy Frontend (dev/test/prod)

on:
  push:
    branches: ["dev", "test", "main"]
    paths:
      - "frontend/**"
  workflow_dispatch: {}

concurrency:
  group: frontend-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDSDK_CORE_DISABLE_PROMPTS: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 브랜치 → 환경 매핑
      - name: Map branch to environment
        id: map
        run: |
          if [ "${GITHUB_REF_NAME}" = "dev" ]; then
            echo "ENV=DEV"         >> $GITHUB_OUTPUT
            echo "ENV_LOWER=dev"   >> $GITHUB_OUTPUT
            echo "BUILD_MODE=development" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_REF_NAME}" = "test" ]; then
            echo "ENV=TEST"        >> $GITHUB_OUTPUT
            echo "ENV_LOWER=test"  >> $GITHUB_OUTPUT
            echo "BUILD_MODE=test" >> $GITHUB_OUTPUT
          else
            echo "ENV=PROD"        >> $GITHUB_OUTPUT
            echo "ENV_LOWER=prod"  >> $GITHUB_OUTPUT
            echo "BUILD_MODE=production" >> $GITHUB_OUTPUT
          fi

      # 1) GCP 인증 (레포 시크릿에 GCP_SA_KEY_DEV/TEST/PROD 가 JSON 전체로 있어야 함)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets[format('GCP_SA_KEY_{0}', steps.map.outputs.ENV)] }}

      # 2) gcloud 설치 + 프로젝트 설정
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets[format('GCP_PROJECT_ID_{0}', steps.map.outputs.ENV)] }}

      # ※ API 활성화는 콘솔에서 한 번만 해두세요.
      # - name: Enable required APIs
      #   run: |
      #     gcloud services enable run.googleapis.com artifactregistry.googleapis.com cloudbuild.googleapis.com

      # 3) Cloud Build로 이미지 빌드 & 푸시 (BUILD_MODE 전달)
      - name: Build & Push Docker image (with BUILD_MODE)
        env:
          PROJECT_ID: ${{ secrets[format('GCP_PROJECT_ID_{0}', steps.map.outputs.ENV)] }}
          REGION:     ${{ secrets.GCP_REGION }}
          AR_REPO:    ${{ secrets.AR_REPO }}
          ENV_LOWER:  ${{ steps.map.outputs.ENV_LOWER }}
          BUILD_MODE: ${{ steps.map.outputs.BUILD_MODE }}
        run: |
          TAG=${GITHUB_SHA}
          gcloud builds submit frontend \
            --tag "${REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO}/frontend-${ENV_LOWER}:${TAG}" \
            --region "${REGION}" \
            -- \
            --build-arg BUILD_MODE="${BUILD_MODE}"

      # 4) Cloud Run 배포
      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: ${{ secrets[format('GCP_PROJECT_ID_{0}', steps.map.outputs.ENV)] }}
          REGION:     ${{ secrets.GCP_REGION }}
          AR_REPO:    ${{ secrets.AR_REPO }}
          ENV_LOWER:  ${{ steps.map.outputs.ENV_LOWER }}
          RUNTIME_SA: ${{ secrets[format('RUNTIME_SA_{0}', steps.map.outputs.ENV)] }}
        run: |
          TAG=${GITHUB_SHA}
          IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO}/frontend-${ENV_LOWER}:${TAG}"
          SERVICE="frontend-${ENV_LOWER}"

          gcloud run deploy "${SERVICE}" \
            --image="${IMAGE}" \
            --region="${REGION}" \
            --platform=managed \
            --port=8080 \
            --allow-unauthenticated \
            --service-account="${RUNTIME_SA}" \
            --quiet